### ISSUE TITLE
Allow configuration of swc-loader `include` for monorepos

### ISSUE THREAD

**Issue by rclmenezes** [extension-js/extension.js#217]
Hi,

I'm using extension.js within a monorepo, and the directory structure looks something like this:

```
/my-repo
    /extension
    /packages
        /package-a
        /package-b
```

These internal packages have uncompiled typescript, some of which are used by the extension pacakage. Unfortunately, this means that `extension dev` fails because there is no webpack loader for `.ts` files outside of manifestPath. I get an error like this:

```
ERROR in ../packages/sdk/src/types.ts 4:14
Module parse failed: Unexpected token (4:14)
File was processed with these loaders:
 * ../node_modules/.pnpm/@pmmmwh+react-refresh-webpack-plugin@0.5.15_react-refresh@0.14.2_webpack-dev-server@5.1.0_webpack@5.92.1/node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js
You may need an additional loader to handle the result of these loaders.
| __webpack_require__.$Refresh$.runtime = __react_refresh_runtime__;
| 
> import { type MessageContent, type RoleType } from "@internal/chat";
```

The problem is due to the way [we configure swc-loader within `JsFrameworksPlugin`](https://github.com/extension-js/extension.js/blob/f5e78b1d2e8d8cae864c2c38bfa82d579db2eadc/programs/develop/webpack/plugin-js-frameworks/index.ts#L43C7-L53C15):

```
{
        test: /\.(js|mjs|jsx|mjsx|ts|mts|tsx|mtsx)$/,
        include: [path.dirname(this.manifestPath)],       <---
        exclude: /node_modules/,
        use: {
          loader: require.resolve('swc-loader'),
          options: {
            sync: true,
            module: {
              type: 'es6'
            },
```

If I patch `JsFrameworksPlugin` so include is `[path.dirname(this.manifestPath), "../packages"]`, then my extension compiles correctly. For now, I simply moved manifest.json to the top-level package, which obviously isn't ideal.

Can we add an `swcIncludeList` option to extension.config.js to support monorepos?

Alternatively, I _could_ compile my internal packages before developing on extension but pleh that's no fun

**Comment by cezaraugusto** [comment]
hey @rclmenezes you can create a `scripts/` folder at the same level as your manifest.json and reference these packages. Extension.js will treat any js-like file within the `scripts/` folder as a top-level entrypoint (like background or content_scripts defined in the manifest file). let me know if that address your use case

```diff
/my-repo
    /extension
+       /scripts
+           package-a.ts # which imports ../../packages/package-a
+           package-b.ts # which imports ../../packages/package-b
    /packages
        /package-a
        /package-b
```

**Comment by rclmenezes** [comment]
Valeu, mermão!

Worked great. I did:

```
// extension/scripts/package-a.ts

export * from "@repo/package-a";
```

That said -- I would still recommend adding an option to append to swc-loader's includeList. My autocomplete still recommends `import foo from @repo/package-a`. It's minorly annoying to have to remember to replace `@repo/package-a` with `~/scripts/package-a` every time :)

Obrigado!

**Comment by cezaraugusto** [comment]
haha beleza!

for the SWC support, it is theoretically possible to support a config file override via `.swcrc` (through swc-loader). for the autocomplete, maybe hacking `tsconfig.json` could help, but haven't relly tried it out.

thanks for using Extension.js and pls report anything else you believe should be working!

obrigado!

**Comment by rclmenezes** [comment]
Oops, so it turns out I was still compiling my packages. That meant that importing from "../scripts/package-a" didn't actually work -- it was relying on the compiled product.

I found a pretty clean solution by adding a custom plugin in extension.config.js:

```javascript
const path = require("path");

class MonorepoPlugin {
  apply(compiler) {
    const monorepoRoot = path.join(process.cwd(), "..");

    compiler.options.module.rules = [
      {
        test: /\.(js|mjs|jsx|mjsx|ts|mts|tsx|mtsx)$/,
        include: [monorepoRoot],
        exclude: /node_modules/,
        use: {
          loader: require.resolve("swc-loader"),
          options: {
            sync: true,
            module: {
              type: "es6",
            },
            minify: compiler.options.mode === "production",
            isModule: true,
            jsc: {
              target: "es2016",
              parser: {
                syntax: "typescript",
                tsx: true,
                jsx: true,
                dynamicImport: true,
              },
              transform: {
                react: {
                  development: compiler.options.mode === "development",
                  refresh: compiler.options.mode === "development",
                  runtime: "automatic",
                  importSource: "react",
                },
              },
            },
          },
        },
      },
      ...compiler.options.module.rules,
    ];
  }
}

/** @type {import('extension').FileConfig} */
module.exports = {
  config: (config) => {
    config.plugins.push(new MonorepoPlugin());

    return config;
  },
};
```

It works perfectly and hot module reloading works as well.

Here's a repo to replicate:
https://github.com/rclmenezes/extension-monorepo-test

Interestingly, I can't modify swc-loader within extension.config.js. When I add `console.log(compiler.options.module.rules)` -- I never see swc-loader appear! Pretty odd.

**Comment by cezaraugusto** [comment]
thanks for the hints and demo, going to take a look.

**Comment by paschaldev** [comment]
@rclmenezes The mono repo plugin didn't work for me. I still see the same errors.

```zsh
ERROR in ../../packages/webui/src/lib/providers/user-profile-provider.tsx 7:12
Module parse failed: Unexpected token (7:12)
File was processed with these loaders:
 * ../../node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js
You may need an additional loader to handle the result of these loaders.
|
| import { createContext, useMemo } from 'react';
> import type { PropsWithChildren } from 'react';
|
| import { api } from '@/convex/_generated/api';
```

**Comment by rclmenezes** [comment]
Your `monorepoRoot` isn't set right

I did only one level up because my `extension` package was top-level to the overall package: 

```typescript
const monorepoRoot = path.join(process.cwd(), "..");
```

Based on `../../node_modules`, it looks like you need two levels up:

```typescript
const monorepoRoot = path.join(process.cwd(), "../..");
```

**Comment by paschaldev** [comment]
@rclmenezes I did two levels up

<img width="407" alt="Screenshot 2024-12-20 at 07 52 34" src="https://github.com/user-attachments/assets/ba533c15-7f15-42a2-a599-3521633b071b" />

In your example repo https://github.com/rclmenezes/extension-monorepo-test, I do not see an import from the packages directory or did I miss it?

I have this structure, I use path aliases. In the `tsconfig.json` in `extension`, I have set this path alias

### tsconfig.json
```json
"paths": {
  "~/*": ["../../packages/webui/src/*"]
}
```

### scripts.tsx

I have this import in scripts that loads a components from webui

```tsx
import { UserProfileContextProvider } from '~/lib/providers/user-profile-provider';
```

```bash
root
  /apps
      /web
      /extension
        script.tsx
        tsconfig.json
  /packages
      /webui
```

**Comment by paschaldev** [comment]
I updated `package.json`, I removed `type: module`, the error has changed

<img width="1168" alt="Screenshot 2024-12-20 at 12 01 34" src="https://github.com/user-attachments/assets/9e34b1ac-b929-4beb-ad30-89725b12c63c" />

**Comment by rclmenezes** [comment]
I think I see the problem. You're using relative imports within your
extension to access files from a different package (e.g. import from
../../../ or ~/blah)

In my example, I'm using "internal packages." Here, I am importing from
***@***.***/sdk:
https://github.com/rclmenezes/extension-monorepo-test/blob/main/extension/action/Action.tsx#L3

Which is a package I defined here (note the  "exports" and "types" settings
in particular):
https://github.com/rclmenezes/extension-monorepo-test/blob/main/packages/sdk/package.json

Yes, you do need "type": module here for es5 import/exports.

One more thing -- I'm using pnpm. These internal packages may not work in
npm / yarn unless you add some other stuff

Good luck!

**Comment by paschaldev** [comment]
@rclmenezes Thank you. Everything works fine now. I use relative imports with alias. 

- Remove `"type": "module"` from `package.json` in extension monorepo directory. Without this, I was getting a `ERR_REQUIRE_ESM` with the `extension.config.js` file 
- I had to remove additional css style rule in the plugin config. This was the cause of the postcss loader issue I shared earlier. The error was caused by conflicts

Within my extension folder, I can 
`import Foo from ~/packages/webui/components/foo`

**Comment by rclmenezes** [comment]
Glad it worked but I gotta say — importing directly from a different
package is not be a good idea.

If webui installed a package that extension doesn’t use, then your import
will break. I really recommend using the internal packages pattern instead.
